---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: pages
  label: Pages
  create: all
  match: "**/*"
upload_dir: ''
public_path: https://res.cloudinary.com/jimsimages/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: _site/
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npx @11ty/eleventy --serve
